#!/usr/bin/env python

Import("env")

env.drivers_sources = []

# OS drivers
SConscript("unix/SCsub")
SConscript("windows/SCsub")

# Sounds drivers
SConscript("alsa/SCsub")
SConscript("coreaudio/SCsub")
SConscript("pulseaudio/SCsub")
if env["platform"] == "windows":
    SConscript("wasapi/SCsub")
if env["xaudio2"]:
    SConscript("xaudio2/SCsub")

# Midi drivers
SConscript("alsamidi/SCsub")
SConscript("coremidi/SCsub")
SConscript("winmidi/SCsub")

# Graphics drivers
print("test print:")
print(env["opengl2"])
print(env["opengl3"])
print(env["vulkan"])

if env["vulkan"]:
    SConscript("vulkan/SCsub")
if env["d3d12"]:
    SConscript("d3d12/SCsub")
if env["opengl3"] or env["opengl2"]:
    SConscript("gl_context/SCsub")
    SConscript("gles_common/SCsub")
    SConscript("egl/SCsub")
    if env["opengl2"]:
        SConscript("gles2/SCsub")
    if env["opengl3"]:
        SConscript("gles3/SCsub")

# Core dependencies
SConscript("png/SCsub")

env.add_source_files(env.drivers_sources, "*.cpp")

lib = env.add_library("drivers", env.drivers_sources)
env.Prepend(LIBS=[lib])
